[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
BAT = "c0cd4b16-88b7-57fa-983b-ab80aecada7e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ChangesOfVariables = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DensityInterface = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
EmpiricalDistributions = "0bbb1fad-0f24-45fe-94a4-415852c5cc3b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LegendDSP = "e6d7a502-be5c-5049-a927-8d60e566555d"
LegendDataTypes = "99e09c13-5545-5ee2-bfa2-77f358fb75d8"
LegendHDF5IO = "c9265ca6-b027-5446-b1a4-febfa8dd10b0"
LegendTextIO = "c397c909-374d-579b-8af3-fa3aa4f02e89"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Neptune = "6741aa20-66dc-42c8-a8ae-3740631035cd"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
ParallelProcessingTools = "8e8a01fc-6193-5ca1-a2f1-20776dae4199"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RadiationDetectorDSP = "afd6e06f-c550-5763-af36-7391d39e46ec"
RadiationDetectorSignals = "bf2c0563-65cf-5db2-a620-ceb7de82658c"
RadiationSpectra = "4f207c7e-01da-51d7-a1a0-c8c06dd1d883"
Random123 = "74087812-796a-5b5d-8853-05524746bad3"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
SolidStateDetectors = "71e43887-2bd9-5f77-aebd-47f656f0a3f0"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
ValueShapes = "136a8f8c-c49b-4edb-8b98-f3d64d48be8f"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BAT = "3"
RadiationDetectorSignals = "0.1"
RadiationSpectra = "0.5"
SolidStateDetectors = "0.7"
julia = "1.7"
